/*
  create your Firebase auth setup with FIREBASE AUTHENTICATION
  paste your own config object into a file called .configuration.ts in the services folder.
  Your configuation keys and values are generated by firebase
*/


// Initialize Firebase
export let config = {
  apiKey: 'Your api key',
  authDomain: 'Your auth domain',
  databaseURL: 'your Database url',
  projectId: 'your project id',
  storageBucket: 'your code',
  messagingSenderId: 'your code'
};
